const PDFDocument = require('pdfkit');
const path = require('path');
const fs = require('fs');

const { Company, Intern } = require('../models');

exports.generateHTEList = async (req, res) => {
  let doc;

  try {
    const companies = await Company.findAll({
      include: [
        {
          model: Intern,
          as: 'AssignedInterns',
          required: false,
        },
      ],
      order: [['name', 'ASC']],
    });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'inline; filename=hte_list.pdf');

    doc = new PDFDocument({
      size: 'Legal',
      layout: 'landscape',
      margin: 40,
    });

    doc.pipe(res);

    const startX = 40;
    const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

    const tableWidth = pageWidth;

    /* =============================
       HELPER: CALCULATE MOA VALIDITY
    ============================== */
    const calculateMOAValidity = (moaEnd) => {
      if (!moaEnd) return 'N/A';

      const today = new Date();
      today.setHours(0, 0, 0, 0);

      const endDate = new Date(moaEnd);
      endDate.setHours(0, 0, 0, 0);

      const diffTime = endDate - today;
      const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

      if (diffDays < 0) {
        return 'Expired';
      } else if (diffDays === 0) {
        return 'Expires Today';
      } else if (diffDays === 1) {
        return '1 day';
      } else if (diffDays <= 30) {
        return `${diffDays} days`;
      } else if (diffDays <= 365) {
        const months = Math.floor(diffDays / 30);
        return months === 1 ? '1 month' : `${months} months`;
      } else {
        const years = Math.floor(diffDays / 365);
        const remainingMonths = Math.floor((diffDays % 365) / 30);
        if (remainingMonths === 0) {
          return years === 1 ? '1 year' : `${years} years`;
        }
        return `${years}y ${remainingMonths}m`;
      }
    };

    /* =============================
       HEADER + LOGO
    ============================== */
    const generateHeader = () => {
      const logoPath = path.join(process.cwd(), 'pup_1904_flat.png');

      if (fs.existsSync(logoPath)) {
        doc.image(logoPath, 40, 35, { width: 50 });
      }

      doc
        .fillColor('black')
        .fontSize(8)
        .font('Helvetica')
        .text('REPUBLIC OF THE PHILIPPINES', 100, 40)
        .fontSize(10)
        .font('Helvetica-Bold')
        .text('POLYTECHNIC UNIVERSITY OF THE PHILIPPINES', 100, 52)
        .fontSize(8)
        .font('Helvetica')
        .text('OFFICE OF THE VICE PRESIDENT FOR CAMPUSES', 100, 66)
        .fontSize(10)
        .font('Helvetica-Bold')
        .text('MARIVELES, BATAAN CAMPUS', 100, 78);
      doc
        .moveTo(doc.page.margins.left, 100)
        .lineTo(doc.page.width - doc.page.margins.right, 100)
        .stroke();

      doc.moveDown(2);
      doc.fontSize(14).font('Helvetica-Bold').text('HOST TRAINING ESTABLISHMENTS LIST', {
        align: 'center',
      });

      doc.moveDown(1);
      return doc.y;
    };

    /* =============================
       TABLE HEADER
    ============================== */
    const drawTableHeader = (y) => {
      doc.rect(startX, y, tableWidth, 22).fill('#800000');
      doc.fillColor('white').fontSize(8).font('Helvetica-Bold');

      doc.text('NO.', startX + 5, y + 6);
      doc.text('HTE NAME', startX + 35, y + 6);
      doc.text('EMAIL', startX + 190, y + 6);
      doc.text('ADDRESS', startX + 300, y + 6);
      doc.text('SUPERVISOR', startX + 470, y + 6);
      doc.text('NATURE OF BUSINESS', startX + 580, y + 6);
      doc.text('MOA VALIDITY', startX + 710, y + 6, { width: 80, align: 'center' });
      doc.text('INTERNS', startX + 795, y + 6, { width: 60, align: 'center' });

      return y + 22;
    };

    /* =============================
       INITIAL PAGE
    ============================== */
    let currentY = generateHeader();

    // ========== FOOTER AT TOP ==========
    const currentDate = new Date().toLocaleString('en-US', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: true,
    });
    doc
      .fontSize(8)
      .font('Helvetica-Oblique')
      .fillColor('#666666')
      .text(`Generated by PUPSINAG (PUP System for Internship Navigation and Guidance) on ${currentDate}`, { align: 'center' });
    doc.moveDown(0.5);
    doc.fillColor('black').font('Helvetica');

    currentY = doc.y;
    currentY = drawTableHeader(currentY);

    doc.fillColor('black').font('Helvetica').fontSize(8);

    /* =============================
       TABLE ROWS
    ============================== */
    companies.forEach((company, index) => {
      const addressWidth = 150;
      const natureWidth = 120;

      const rowHeight = Math.max(
        doc.heightOfString(company.address || 'N/A', { width: addressWidth }) + 10,
        doc.heightOfString(company.natureOfBusiness || 'N/A', { width: natureWidth }) + 10,
        22,
      );

      if (currentY + rowHeight > 530) {
        doc.addPage();
        currentY = generateHeader();
        currentY = drawTableHeader(currentY);
        doc.fillColor('black').font('Helvetica').fontSize(8);
      }

      doc.rect(startX, currentY, tableWidth, rowHeight).strokeColor('#CCCCCC').stroke();

      doc.text(index + 1, startX + 5, currentY + 6);
      doc.text(company.name || 'N/A', startX + 35, currentY + 6, { width: 145 });
      doc.text(company.email || 'N/A', startX + 190, currentY + 6, { width: 105 });
      doc.text(company.address || 'N/A', startX + 300, currentY + 6, { width: addressWidth });
      doc.text(company.supervisorName || 'N/A', startX + 470, currentY + 6, { width: 100 });
      doc.text(company.natureOfBusiness || 'N/A', startX + 580, currentY + 6, { width: natureWidth });

      // ✅ FIXED: Calculate remaining time until MOA expires
      const moaValidity = calculateMOAValidity(company.moaEnd);

      doc.text(moaValidity, startX + 710, currentY + 6, { width: 80, align: 'center' });

      const internCount = Array.isArray(company.AssignedInterns) ? company.AssignedInterns.length : 0;
      doc.text(internCount, startX + 795, currentY + 6, { width: 60, align: 'center' });

      currentY += rowHeight;
    });

    doc.end();
  } catch (err) {
    console.error('❌ HTE LIST ERROR:', err);
    if (doc) doc.end();
    if (!res.headersSent) {
      res.status(500).json({ message: 'Failed to generate HTE List' });
    }
  }
};
