const PDFDocument = require('pdfkit');
const path = require('path');
const fs = require('fs');
const { User } = require('../models');

exports.generateAdviserList = async (req, res) => {
  let doc;

  try {
    // Get ALL advisers from the system
    const advisers = await User.findAll({
      where: {
        role: 'adviser',
      },
      order: [['lastName', 'ASC']],
    });

    /* =============================
       PDF SETUP
    ============================== */
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'inline; filename=advisers_list.pdf');

    doc = new PDFDocument({
      size: 'Legal',
      layout: 'landscape',
      margin: 40,
    });

    doc.pipe(res);

    const startX = doc.page.margins.left;
    const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

    /* =============================
       HEADER
    ============================== */
    const logoPath = path.join(process.cwd(), 'pup_1904_flat.png');
    if (fs.existsSync(logoPath)) {
      doc.image(logoPath, startX, 35, { width: 50 });
    }

    doc
      .fontSize(8)
      .text('REPUBLIC OF THE PHILIPPINES', startX + 70, 40)
      .fontSize(10)
      .font('Helvetica-Bold')
      .text('POLYTECHNIC UNIVERSITY OF THE PHILIPPINES', startX + 70, 52)
      .fontSize(8)
      .font('Helvetica')
      .text('OFFICE OF THE VICE PRESIDENT FOR CAMPUSES', startX + 70, 66)
      .fontSize(10)
      .font('Helvetica-Bold')
      .text('MARIVELES, BATAAN CAMPUS', startX + 70, 78);

    doc
      .moveTo(startX, 100)
      .lineTo(doc.page.width - doc.page.margins.right, 100)
      .stroke();

    doc.moveDown(2);
    doc.fontSize(14).font('Helvetica-Bold').text('LIST OF ADVISERS', { align: 'center' });

    doc.moveDown(1);

    // ========== FOOTER AT TOP ==========
    const currentDate = new Date().toLocaleString('en-US', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: true,
    });
    doc
      .fontSize(8)
      .font('Helvetica-Oblique')
      .fillColor('#666666')
      .text(`Generated by PUPSINAG (PUP System for Internship Navigation and Guidance) on ${currentDate}`, { align: 'center' });
    
    doc.moveDown(0.5);

    /* =============================
       TABLE HEADER
    ============================== */
    let y = doc.y;
    const colWidths = {
      no: 45,
      firstName: 100,
      lastName: 120,
      email: 130,
      program: 360,
      yearSection: 130,
    };

    const colPositions = {
      no: startX,
      firstName: startX + colWidths.no,
      lastName: startX + colWidths.no + colWidths.firstName,
      email: startX + colWidths.no + colWidths.firstName + colWidths.lastName,
      program: startX + colWidths.no + colWidths.firstName + colWidths.lastName + colWidths.email,
      yearSection:
        startX + colWidths.no + colWidths.firstName + colWidths.lastName + colWidths.email + colWidths.program,
    };

    doc.rect(startX, y, pageWidth, 30).fill('#800000');

    doc.fillColor('white').fontSize(10).font('Helvetica-Bold');
    doc.text('NO.', colPositions.no, y + 10, { width: colWidths.no, align: 'center' });
    doc.text('FIRST NAME', colPositions.firstName, y + 10, { width: colWidths.firstName, align: 'center' });
    doc.text('LAST NAME', colPositions.lastName, y + 10, { width: colWidths.lastName, align: 'center' });
    doc.text('EMAIL', colPositions.email, y + 10, { width: colWidths.email, align: 'center' });
    doc.text('PROGRAM', colPositions.program, y + 10, { width: colWidths.program, align: 'center' });
    doc.text('YEAR & SECTION', colPositions.yearSection, y + 10, { width: colWidths.yearSection, align: 'center' });

    y += 30;
    doc.fillColor('black').font('Helvetica').fontSize(9);

    /* =============================
       TABLE ROWS
    ============================== */
    advisers.forEach((adviser, index) => {
      if (y > doc.page.height - 60) {
        doc.addPage();
        y = doc.page.margins.top;

        // Redraw header for new page
        doc.rect(startX, y, pageWidth, 30).fill('#800000');
        doc.fillColor('white').fontSize(10).font('Helvetica-Bold');
        doc.text('NO.', colPositions.no, y + 10, { width: colWidths.no, align: 'center' });
        doc.text('FIRST NAME', colPositions.firstName, y + 10, { width: colWidths.firstName, align: 'center' });
        doc.text('LAST NAME', colPositions.lastName, y + 10, { width: colWidths.lastName, align: 'center' });
        doc.text('EMAIL', colPositions.email, y + 10, { width: colWidths.email, align: 'center' });
        doc.text('PROGRAM', colPositions.program, y + 10, { width: colWidths.program, align: 'center' });
        doc.text('YEAR & SECTION', colPositions.yearSection, y + 10, { width: colWidths.yearSection, align: 'center' });
        y += 30;
        doc.fillColor('black').font('Helvetica').fontSize(9);
      }

      doc.rect(startX, y, pageWidth, 28).stroke('#CCCCCC');
      doc.text(index + 1, colPositions.no, y + 7, { width: colWidths.no, align: 'center' });
      doc.text(adviser.firstName || 'N/A', colPositions.firstName, y + 7, { width: colWidths.firstName });
      doc.text(adviser.lastName || 'N/A', colPositions.lastName, y + 7, { width: colWidths.lastName });
      doc.text(adviser.email || 'N/A', colPositions.email, y + 7, { width: colWidths.email });
      doc.text(adviser.program || 'N/A', colPositions.program, y + 7, { width: colWidths.program, ellipsis: true });
      const yearSection = adviser.yearSection || 'NONE';
      doc.text(yearSection, colPositions.yearSection, y + 7, { width: colWidths.yearSection });
      y += 28;
    });

    doc.end();
  } catch (error) {
    console.error('❌ ADVISER LIST ERROR:', error.message);
    if (doc) doc.end();
    if (!res.headersSent) {
      res.status(500).json({ message: 'Failed to generate Adviser List PDF' });
    }
  }
};
