const PDFDocument = require('pdfkit');
const path = require('path');
const fs = require('fs');
const sequelize = require('../config/database');
const { Op } = require('sequelize');

const { Intern, User, Company, InternEvaluation, InternEvaluationItem, Supervisor } = require('../models');

exports.generateInternEvaluationReport = async (req, res) => {
  let doc;

  try {
    const { program, year_section } = req.body;
    if (!program) {
      return res.status(400).json({ message: 'Program is required' });
    }

    /* =============================
       FETCH DATA
    ============================== */
    let whereClause = {
      program: program,
    };

    // Only add year_section filter if provided
    if (year_section) {
      whereClause.year_section = year_section;
    }

    const interns = await Intern.findAll({
      where: whereClause,
      include: [
        { model: User, as: 'User', attributes: ['firstName', 'lastName', 'email'] },
        { model: Company, as: 'company', attributes: ['name'] },
        { model: Supervisor, as: 'Supervisor', attributes: ['name'] },
        {
          model: InternEvaluation,
          as: 'Evaluations',
          attributes: ['id', 'intern_id', 'internName', 'section', 'hteName', 'jobDescription', 'totalScore', 'date'],
          include: [{ model: InternEvaluationItem, as: 'items', attributes: ['category', 'score'] }],
        },
      ],
      order: [[{ model: User, as: 'User' }, 'lastName', 'ASC']],
    });

    /* =============================
       PDF SETUP
    ============================== */
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'inline; filename=interns_evaluation.pdf');

    doc = new PDFDocument({
      size: 'Legal',
      layout: 'landscape',
      margin: 40,
    });

    doc.pipe(res);

    const startX = doc.page.margins.left;
    const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

    /* =============================
       HEADER
    ============================== */
    const logoPath = path.join(process.cwd(), 'pup_1904_flat.png');
    if (fs.existsSync(logoPath)) {
      doc.image(logoPath, startX, 35, { width: 50 });
    }

    doc
      .fontSize(8)
      .text('REPUBLIC OF THE PHILIPPINES', startX + 70, 40)
      .fontSize(10)
      .font('Helvetica-Bold')
      .text('POLYTECHNIC UNIVERSITY OF THE PHILIPPINES', startX + 70, 52)
      .fontSize(8)
      .font('Helvetica')
      .text('OFFICE OF THE VICE PRESIDENT FOR CAMPUSES', startX + 70, 66)
      .fontSize(10)
      .font('Helvetica-Bold')
      .text('MARIVELES, BATAAN CAMPUS', startX + 70, 78);

    doc
      .moveTo(startX, 100)
      .lineTo(doc.page.width - doc.page.margins.right, 100)
      .stroke();

    doc.moveDown(2);
    doc.fontSize(14).font('Helvetica-Bold').text('INTERNS EVALUATION', { align: 'center' });

    doc.moveDown(0.5);
    doc.fontSize(10).font('Helvetica-Bold').text(`PROGRAM: ${program.toUpperCase()}`, { align: 'center' });

    doc.moveDown(1);

    // ========== FOOTER AT TOP ==========
    const currentDate = new Date().toLocaleString('en-US', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: true,
    });
    doc
      .fontSize(8)
      .font('Helvetica-Oblique')
      .fillColor('#666666')
      .text(`Generated by PUPSINAG (PUP System for Internship Navigation and Guidance) on ${currentDate}`, { align: 'center' });
    doc.moveDown(0.5);
    doc.fillColor('black').font('Helvetica');

    /* =============================
       TABLE HEADER
    ============================== */
    let y = doc.y;
    doc.rect(startX, y, pageWidth, 26).fill('#800000');
    doc.fillColor('white').fontSize(9).font('Helvetica-Bold');

    // Adjusted widths: Reduced Name, standardized score columns
    const cols = {
      no: { x: startX, w: 40 },
      name: { x: startX + 40, w: 200 },

      character: { x: startX + 240, w: 115 },
      competence: { x: startX + 355, w: 115 },
      supervisor: { x: startX + 470, w: 115 },
      company: { x: startX + 585, w: 115 },

      mean: { x: startX + 700, w: 100 },
    };

    doc.text('NO.', cols.no.x, y + 8, { width: cols.no.w, align: 'center' });
    doc.text('STUDENT NAME', cols.name.x + 10, y + 8, { width: cols.name.w - 10 });
    doc.text('CHARACTER', cols.character.x, y + 8, { width: cols.character.w, align: 'center' });
    doc.text('COMPETENCE', cols.competence.x, y + 8, { width: cols.competence.w, align: 'center' });
    doc.text('SUPERVISOR', cols.supervisor.x, y + 8, { width: cols.supervisor.w, align: 'center' });
    doc.text('COMPANY / HTE', cols.company.x, y + 8, { width: cols.company.w, align: 'center' });
    doc.text('OVERALL MEAN', cols.mean.x, y + 8, { width: cols.mean.w, align: 'center' });

    y += 26;
    doc.fillColor('black').font('Helvetica').fontSize(9);

    /* =============================
       TABLE ROWS
    ============================== */
    interns.forEach((intern, index) => {
      if (y > doc.page.height - 60) {
        doc.addPage();
        y = doc.page.margins.top;
        // Redraw Header on new page
        doc.rect(startX, y, pageWidth, 26).fill('#800000');
        doc.fillColor('white').fontSize(9).font('Helvetica-Bold');
        doc.text('NO.', cols.no.x, y + 8, { width: cols.no.w, align: 'center' });
        doc.text('STUDENT NAME', cols.name.x + 10, y + 8, { width: cols.name.w - 10 });
        doc.text('CHARACTER', cols.character.x, y + 8, { width: cols.character.w, align: 'center' });
        doc.text('COMPETENCE', cols.competence.x, y + 8, { width: cols.competence.w, align: 'center' });
        doc.text('SUPERVISOR', cols.supervisor.x, y + 8, { width: cols.supervisor.w, align: 'center' });
        doc.text('COMPANY / HTE', cols.company.x, y + 8, { width: cols.company.w, align: 'center' });
        doc.text('OVERALL MEAN', cols.mean.x, y + 8, { width: cols.mean.w, align: 'center' });
        y += 26;
        doc.fillColor('black').font('Helvetica').fontSize(9);
      }
      // Defensive: skip if no User
      if (!intern.User) return;
      const evaluation = Array.isArray(intern.Evaluations) ? intern.Evaluations[0] : null;
      const items = evaluation && Array.isArray(evaluation.items) ? evaluation.items : [];
      const categoryScores = {
        CHARACTER: [],
        COMPETENCE: [],
      };
      items.forEach((item) => {
        if (item && categoryScores[item.category]) {
          categoryScores[item.category].push(Number(item.score));
        }
      });
      // Average per category
      const characterAvg =
        categoryScores.CHARACTER.length > 0
          ? categoryScores.CHARACTER.reduce((a, b) => a + b, 0) / categoryScores.CHARACTER.length
          : null;
      const competenceAvg =
        categoryScores.COMPETENCE.length > 0
          ? categoryScores.COMPETENCE.reduce((a, b) => a + b, 0) / categoryScores.COMPETENCE.length
          : null;
      // Overall mean
      const validAverages = [characterAvg, competenceAvg].filter((v) => typeof v === 'number');
      const mean =
        validAverages.length > 0 ? (validAverages.reduce((a, b) => a + b, 0) / validAverages.length).toFixed(2) : 'N/A';
      // Draw Row Border
      doc.rect(startX, y, pageWidth, 20).stroke('#CCCCCC');
      // Row Data
      doc.text(index + 1, cols.no.x, y + 6, { width: cols.no.w, align: 'center' });
      doc.text(
        `${intern.User.lastName ? intern.User.lastName.toUpperCase() : 'N/A'}, ${intern.User.firstName ? intern.User.firstName.toUpperCase() : 'N/A'}`,
        cols.name.x + 10,
        y + 6,
        { width: cols.name.w - 10, ellipsis: true },
      );
      doc.text(characterAvg !== null ? characterAvg.toFixed(2) : 'N/A', cols.character.x, y + 6, {
        width: cols.character.w,
        align: 'center',
      });
      doc.text(competenceAvg !== null ? competenceAvg.toFixed(2) : 'N/A', cols.competence.x, y + 6, {
        width: cols.competence.w,
        align: 'center',
      });
      const supervisorName = intern.Supervisor?.name || 'N/A';
      const companyName = intern.company?.name || 'N/A';
      doc.text(supervisorName ? supervisorName.toUpperCase() : 'N/A', cols.supervisor.x, y + 6, {
        width: cols.supervisor.w,
        align: 'center',
        ellipsis: true,
      });
      doc.text(companyName ? companyName.toUpperCase() : 'N/A', cols.company.x, y + 6, {
        width: cols.company.w,
        align: 'center',
        ellipsis: true,
      });
      doc.text(mean, cols.mean.x, y + 6, { width: cols.mean.w, align: 'center' });
      y += 20;
    });

    doc.end();
  } catch (err) {
    console.error('❌ INTERN EVALUATION REPORT ERROR:', err);
    console.error('Error stack:', err.stack);
    if (doc) doc.end();
    if (!res.headersSent) {
      res.status(500).json({
        message: 'Failed to generate Intern Evaluation report',
        error: err.message,
      });
    }
  }
};
