const PDFDocument = require('pdfkit');
const path = require('path');
const fs = require('fs');

const { Intern, User, Company, InternDocuments } = require('../models');

exports.generateInternList = async (req, res) => {
  let doc;

  try {
    const { program, year_section } = req.body;
    if (!program) {
      return res.status(400).json({ message: 'Program is required' });
    }
    console.log('📄 Generating Intern List for:', program, year_section);
    // Build where clause
    let whereClause = { program };
    if (year_section) {
      whereClause.year_section = year_section;
    }
    /* =============================
       FETCH DATA
    ============================== */
    const interns = await Intern.findAll({
      where: whereClause,
      include: [{ model: User, as: 'User', required: false }],
      order: [[{ model: User, as: 'User' }, 'lastName', 'ASC']],
    });

    const adviser = await User.findOne({
      where: { role: 'adviser', program },
    });
    const adviserName = adviser ? `${adviser.firstName || ''} ${adviser.lastName || ''}`.trim().toUpperCase() : 'N/A';

    /* =============================
       PDF HEADERS
    ============================== */
    const safeProgram = program.replace(/\s+/g, '_');

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `inline; filename=intern_list_${safeProgram}.pdf`);

    doc = new PDFDocument({ size: 'A4', margin: 40 });
    doc.pipe(res);

    /* ✅ FIX: DEFINE PAGE WIDTH */
    const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

    /* =============================
   LOGO
============================== */
    const logoPath = path.join(process.cwd(), 'pup_1904_flat.png');

    console.log('🔍 Logo path:', logoPath);
    console.log('🔍 Exists?', fs.existsSync(logoPath));

    if (fs.existsSync(logoPath)) {
      try {
        const imageBuffer = fs.readFileSync(logoPath);
        console.log('✅ Image loaded, size:', imageBuffer.length, 'bytes');

        doc.image(imageBuffer, 40, 40, { width: 55 });
        console.log('✅ Logo added to PDF!');
      } catch (err) {
        console.error('❌ Error:', err.message);
      }
    } else {
      console.error('❌ Logo not found at:', logoPath);
    }
    /* =============================
       HEADER TEXT
    ============================== */
    doc
      .fontSize(8)
      .text('REPUBLIC OF THE PHILIPPINES', 120, 45)
      .fontSize(10)
      .font('Helvetica-Bold')
      .text('POLYTECHNIC UNIVERSITY OF THE PHILIPPINES', 120, 57)
      .fontSize(8)
      .font('Helvetica')
      .text('OFFICE OF THE VICE PRESIDENT FOR CAMPUSES', 120, 71)
      .fontSize(10)
      .font('Helvetica-Bold')
      .text('MARIVELES, BATAAN CAMPUS', 120, 83);

    doc.moveTo(40, 110).lineTo(555, 110).stroke();

    doc.y = 140;

    doc.fontSize(12).font('Helvetica-Bold').text('LIST OF INTERNS', doc.page.margins.left, doc.y, {
      width: pageWidth,
      align: 'center',
    });

    doc.moveDown(0.3);

    doc.fontSize(10).font('Helvetica-Bold').text(program.toUpperCase(), {
      width: pageWidth,
      align: 'center',
    });

    doc.moveDown(0.2);

    doc.fontSize(9).font('Helvetica').text(`ADVISER: ${adviserName}`, {
      width: pageWidth,
      align: 'center',
    });

    // ========== FOOTER AT TOP ==========
    const currentDate = new Date().toLocaleString('en-US', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: true,
    });
    doc
      .fontSize(8)
      .font('Helvetica-Oblique')
      .fillColor('#666666')
      .text(`Generated by PUPSINAG (PUP System for Internship Navigation and Guidance) on ${currentDate}`, { align: 'center' });

    /* =============================
       TABLE HEADER
    ============================== */
    const tableTop = 200;
    const startX = 40;

    doc.rect(startX, tableTop, 515, 22).fill('#800000');

    doc.fillColor('white').fontSize(7.5).font('Helvetica-Bold');
    doc.text('NO.', startX + 5, tableTop + 6);
    doc.text('STUDENT ID', startX + 45, tableTop + 6);
    doc.text('NAME', startX + 145, tableTop + 6);
    doc.text('EMAIL', startX + 295, tableTop + 6);
    doc.text('GUARDIAN', startX + 425, tableTop + 6);

    /* =============================
       TABLE ROWS
    ============================== */
    let currentY = tableTop + 22;
    doc.fillColor('black').font('Helvetica');

    interns.forEach((intern, index) => {
      const u = intern.User || {};
      const fullName = `${u.lastName || ''}, ${u.firstName || ''} ${u.mi || ''}`.trim().toUpperCase();
      doc.rect(startX, currentY, 515, 18).stroke('#CCCCCC');
      doc.fontSize(7);
      doc.text(index + 1, startX + 5, currentY + 5);
      doc.text(u.studentId || 'N/A', startX + 45, currentY + 5);
      doc.text(fullName !== ',' ? fullName : 'N/A', startX + 145, currentY + 5);
      doc.text(u.email || 'N/A', startX + 295, currentY + 5);
      doc.text(u.guardian || 'N/A', startX + 425, currentY + 5);
      currentY += 18;
      if (currentY > 720) {
        doc.addPage();
        currentY = 50;
      }
    });

    doc.end();
  } catch (err) {
    console.error('❌ PDF ERROR:', err);

    if (doc) {
      try {
        doc.end();
      } catch (_) {}
    }

    if (!res.headersSent) {
      res.status(500).json({ message: 'Failed to generate Intern List PDF' });
    }
  }
};
