const PDFDocument = require('pdfkit');
const path = require('path');
const fs = require('fs');
const { Intern, User, Company, HTEEvaluation } = require('../models');

exports.generateInternToHTEEvaluationSummary = async (req, res) => {
  // DEBUG: Log model attributes to diagnose Sequelize field caching issue
  console.log('HTEEvaluation rawAttributes:', Object.keys(HTEEvaluation.rawAttributes));
  let doc;
  try {
    // Fetch all evaluations (no program filter)
    const evaluations = await HTEEvaluation.findAll({
      attributes: ['id', 'ratings', 'company_id', 'intern_id'],
      include: [
        {
          model: Company,
          as: 'hteCompany',
          attributes: ['id', 'name'],
        },
        {
          model: Intern,
          as: 'intern',
          attributes: ['id', 'user_id'],
          include: [{ model: User, as: 'User', attributes: ['id', 'firstName', 'lastName'] }],
        },
      ],
    });

    // Group by company and calculate mean of all ratings
    const companyMap = {};
    evaluations.forEach((evalItem) => {
      const companyName = evalItem.hteCompany && evalItem.hteCompany.name ? evalItem.hteCompany.name : 'N/A';
      if (!companyMap[companyName]) {
        companyMap[companyName] = { sum: 0, count: 0 };
      }
      let ratingsArr = [];
      if (evalItem.ratings) {
        if (typeof evalItem.ratings === 'string') {
          try {
            ratingsArr = JSON.parse(evalItem.ratings);
          } catch (e) {
            ratingsArr = [];
          }
        } else if (Array.isArray(evalItem.ratings)) {
          ratingsArr = evalItem.ratings;
        }
      }
      ratingsArr.forEach((val) => {
        const num = Number(val);
        if (!isNaN(num)) {
          companyMap[companyName].sum += num;
          companyMap[companyName].count += 1;
        }
      });
    });
    const summaryRows = Object.entries(companyMap).map(([company, data], idx) => ({
      no: idx + 1,
      company,
      mean: data.count > 0 ? (data.sum / data.count).toFixed(2) : 'N/A',
    }));

    // PDF setup
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'inline; filename=intern_to_hte_evaluation_summary.pdf');
    doc = new PDFDocument({ size: 'Legal', layout: 'landscape', margin: 40 });
    doc.pipe(res);
    const startX = doc.page.margins.left;
    const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

    // Header
    const logoPath = path.join(process.cwd(), 'pup_1904_flat.png');
    if (fs.existsSync(logoPath)) {
      doc.image(logoPath, startX, 35, { width: 50 });
    }
    doc
      .fontSize(8)
      .text('REPUBLIC OF THE PHILIPPINES', startX + 70, 40)
      .fontSize(10)
      .font('Helvetica-Bold')
      .text('POLYTECHNIC UNIVERSITY OF THE PHILIPPINES', startX + 70, 52)
      .fontSize(8)
      .font('Helvetica')
      .text('OFFICE OF THE VICE PRESIDENT FOR CAMPUSES', startX + 70, 66)
      .fontSize(10)
      .font('Helvetica-Bold')
      .text('MARIVELES, BATAAN CAMPUS', startX + 70, 78);
    doc
      .moveTo(startX, 100)
      .lineTo(doc.page.width - doc.page.margins.right, 100)
      .stroke();
    doc.moveDown(2);
    doc.fontSize(14).font('Helvetica-Bold').text('INTERN TO HTE EVALUATION SUMMARY', { align: 'center' });
    doc.moveDown(1.5);

    // ========== FOOTER AT TOP ==========
    const currentDate = new Date().toLocaleString('en-US', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: true,
    });
    doc
      .fontSize(8)
      .font('Helvetica-Oblique')
      .fillColor('#666666')
      .text(`Generated by PUPSINAG (PUP System for Internship Navigation and Guidance) on ${currentDate}`, { align: 'center' });
    doc.moveDown(0.5);
    doc.fillColor('black').font('Helvetica');

    // Table header
    let y = doc.y;
    doc.rect(startX, y, pageWidth, 26).fill('#800000');
    doc.fillColor('white').fontSize(9).font('Helvetica-Bold');
    const cols = {
      no: { x: startX, w: 40 },
      company: { x: startX + 40, w: 400 },
      mean: { x: startX + 440, w: 200 },
    };
    doc.text('NO.', cols.no.x, y + 8, { width: cols.no.w, align: 'center' });
    doc.text('COMPANY / HTE NAME', cols.company.x, y + 8, { width: cols.company.w, align: 'center' });
    doc.text('MEAN RESULT', cols.mean.x, y + 8, { width: cols.mean.w, align: 'center' });
    y += 26;
    doc.fillColor('black').font('Helvetica').fontSize(9);

    // Table rows
    summaryRows.forEach((row) => {
      if (y > doc.page.height - 60) {
        doc.addPage();
        y = doc.page.margins.top;
        doc.rect(startX, y, pageWidth, 26).fill('#800000');
        doc.fillColor('white').fontSize(9).font('Helvetica-Bold');
        doc.text('NO.', cols.no.x, y + 8, { width: cols.no.w, align: 'center' });
        doc.text('COMPANY / HTE NAME', cols.company.x, y + 8, { width: cols.company.w, align: 'center' });
        doc.text('MEAN RESULT', cols.mean.x, y + 8, { width: cols.mean.w, align: 'center' });
        y += 26;
        doc.fillColor('black').font('Helvetica').fontSize(9);
      }
      doc.rect(startX, y, pageWidth, 20).stroke('#CCCCCC');
      doc.text(row.no, cols.no.x, y + 6, { width: cols.no.w, align: 'center' });
      doc.text(row.company, cols.company.x, y + 6, { width: cols.company.w, align: 'center', ellipsis: true });
      doc.text(row.mean, cols.mean.x, y + 6, { width: cols.mean.w, align: 'center' });
      y += 20;
    });

    doc.end();
  } catch (err) {
    console.error('❌ INTERN TO HTE EVALUATION SUMMARY ERROR:', err);
    if (err instanceof Error && err.stack) {
      console.error('Stack trace:', err.stack);
    }
    if (doc) doc.end();
    if (!res.headersSent) {
      res.status(500).json({
        message: 'Failed to generate Intern to HTE Evaluation Summary report',
        error: err.message,
        stack: err.stack,
      });
    }
  }
};
