/* eslint-env node */
const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

function ensureSpace(doc, neededSpace) {
  const remaining = doc.page.height - doc.y - doc.page.margins.bottom;

  if (remaining < neededSpace) {
    doc.addPage();
  }
}
function formatLegalDate(dateString) {
  if (!dateString) return '';

  const date = new Date(dateString);
  const day = date.getDate();
  const year = date.getFullYear();
  const month = date.toLocaleString('en-US', { month: 'long' });

  const suffix =
    day % 10 === 1 && day !== 11
      ? 'st'
      : day % 10 === 2 && day !== 12
        ? 'nd'
        : day % 10 === 3 && day !== 13
          ? 'rd'
          : 'th';

  return `${day}${suffix} day of ${month}, ${year}`;
}

module.exports = function generateConsentPDF(data, filename) {
  const uploadsDir = path.join(__dirname, '../uploads');
  if (!fs.existsSync(uploadsDir)) {
    fs.mkdirSync(uploadsDir, { recursive: true });
  }

  const filePath = path.join(uploadsDir, filename);

  const doc = new PDFDocument({
    size: 'LEGAL',
    margins: { top: 72, bottom: 72, left: 72, right: 72 },
  });

  doc.pipe(fs.createWriteStream(filePath));

  // ========== FOOTER AT TOP ==========
  const currentDate = new Date().toLocaleString('en-US', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: true,
  });
  doc
    .fontSize(8)
    .font('Times-Italic')
    .fillColor('#666666')
    .text(`Generated by PUPSINAG (PUP System for Internship Navigation and Guidance) on ${currentDate}`, { align: 'center' });
  doc.moveDown(1);
  doc.fillColor('#000000').font('Times-Roman');

  /* =========================
     TITLE
  ========================= */
  doc.font('Times-Bold').fontSize(14).text('CONSENT FORM', { align: 'center' });

  doc.moveDown(2);

  /* =========================
     BODY PARAGRAPH (MATCHED)
  ========================= */
  const paragraphWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

  const paragraphStyle = {
    width: paragraphWidth,
    align: 'justify',
    textIndent: 30, // 👈 FIRST-LINE INDENT
    lineGap: 4,
    wordSpacing: 0.5,
  };
  doc
    .font('Times-Roman')
    .fontSize(11)
    .text(
      `          We, ${data.studentName} and ${data.guardian}, hereby execute this Consent Form allowing my son/ daughter to undergo on-the-job training/ internship for a minimum of ${data.hours} hours beginning ${formatLegalDate(data.startDate)} until ${formatLegalDate(data.endDate)}
 at ${data.hteName} with office address at ${data.hteAddress} in partial fulfillment of the requirement for the ${data.program}.`,
    );

  doc.moveDown(1.5);

  doc.text(
    `           We are aware that the immediate superior within the company will take all the necessary precautions to keep the students safe. The OJT Coordinators will also be there to periodically monitor the performance and safety of the students.`,
  );

  doc.moveDown(1.5);

  doc.text(
    `           We execute this Consent Form in accordance with our free will, realizing the benefits that the student intern shall obtain from the said on-the-job training/ internship program.`,
  );

  /* =========================
     SIGNATURES (SIDE BY SIDE)
  ========================= */
  doc.moveDown(3);

  const y = doc.y;
  const pageWidth = doc.page.width - 144; // margins
  const colWidth = pageWidth / 2 - 20;

  doc.text('______________________________', 72, y, { width: colWidth, align: 'center' });
  doc.text('______________________________', 72 + colWidth + 40, y, { width: colWidth, align: 'center' });

  doc.moveDown(0.5);

  doc.text('(Name and Signature of\nStudent Intern)', 72, doc.y, {
    width: colWidth,
    align: 'center',
  });

  doc.text('(Name and Signature of\nParent/ Guardian)', 72 + colWidth + 40, doc.y - 24, {
    width: colWidth,
    align: 'center',
  });
  doc.moveDown(2);

  /* =========================
   NOTARY SECTION (ABSOLUTE LAYOUT)
========================= */

  // Force notary to stay on same page
  ensureSpace(doc, 320);

  doc.font('Times-Roman').fontSize(11);

  // Save starting Y
  const notaryStartY = doc.y;

  /* --- HEADER --- */
  doc.text('REPUBLIC OF THE PHILIPPINES )', 72, notaryStartY);
  doc.text('CITY OF ____________________ ) S.S.', 72, notaryStartY + 14);

  /* --- OATH PARAGRAPH --- */
  doc.text(
    'Subscribed and sworn to before me, this ______________________________ at ' +
      '______________________________, Philippines, affiants exhibiting valid ' +
      'proofs of their identity as follows:',
    72,
    notaryStartY + 42,
    {
      width: 468,
      align: 'left',
      lineGap: 3,
    },
  );

  /* --- TABLE HEADER --- */
  const tableY = notaryStartY + 95;
  const colX = [72, 222, 372];
  const colW = 120;

  doc.text('Name', colX[0], tableY, { width: colW, align: 'center' });
  doc.text('ID No.', colX[1], tableY, { width: colW, align: 'center' });
  doc.text('Issued at/on', colX[2], tableY, { width: colW, align: 'center' });

  /* --- TABLE ROW (LINE 1) --- */
  const rowY = tableY + 20;

  doc.text('___________________', colX[0], rowY, { width: colW, align: 'center' });
  doc.text('___________________', colX[1], rowY, { width: colW, align: 'center' });
  doc.text('___________________', colX[2], rowY, { width: colW, align: 'center' });

  /* --- TABLE ROW (LINE 2) --- */
  const rowY2 = rowY + 16;

  doc.text('_____________________', colX[0], rowY2, { width: colW, align: 'center' });
  doc.text('_____________________', colX[1], rowY2, { width: colW, align: 'center' });
  doc.text('_____________________', colX[2], rowY2, { width: colW, align: 'center' });

  /* --- ACKNOWLEDGMENT (CENTERED) --- */
  doc.text(
    'They acknowledged to me that the foregoing Consent Form was executed in accordance\n' +
      'with their own free will.',
    72,
    rowY + 45,
    {
      width: 468,
      align: 'center',
      lineGap: 3,
    },
  );

  /* --- NOTARY PUBLIC (FIXED CENTER) --- */
  doc.text('NOTARY PUBLIC', 72, rowY + 95, {
    width: 468,
    align: 'center',
  });

  /* --- NOTARIAL DETAILS (BOTTOM LEFT) --- */
  const footerY = rowY + 135;
  doc.text('Doc. No. _____;', 72, footerY);
  doc.text('Page No. _____;', 72, footerY + 14);
  doc.text('Book No. _____;', 72, footerY + 28);
  doc.text('Series of _____;', 72, footerY + 42);

  // Move cursor past notary block
  doc.y = footerY + 70;

  doc.end();

  return filePath;
};
