/* eslint-env node */
const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

function formatDate(dateString) {
  const date = new Date(dateString);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

module.exports = function generateGeneralRecordPDF(data, res) {
  const doc = new PDFDocument({
    size: 'LETTER',
    layout: 'landscape',
    margins: { top: 50, bottom: 50, left: 50, right: 50 },
  });

  // Pipe directly to response
  doc.pipe(res);

  const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

  /* =========================
     LOGO
  ========================= */
  const logoPath = path.join(__dirname, '..', 'pup_1904_flat.png');

  if (fs.existsSync(logoPath)) {
    try {
      const imageBuffer = fs.readFileSync(logoPath);
      doc.image(imageBuffer, 50, 50, { width: 55 });
    } catch (err) {
      console.error('❌ Logo error:', err.message);
    }
  }

  /* =========================
     HEADER TEXT
  ========================= */
  doc
    .fontSize(8)
    .text('REPUBLIC OF THE PHILIPPINES', 120, 55)
    .fontSize(10)
    .font('Helvetica-Bold')
    .text('POLYTECHNIC UNIVERSITY OF THE PHILIPPINES', 120, 67)
    .fontSize(8)
    .font('Helvetica')
    .text('OFFICE OF THE VICE PRESIDENT FOR CAMPUSES', 120, 81)
    .fontSize(10)
    .font('Helvetica-Bold')
    .text('MARIVELES, BATAAN CAMPUS', 120, 93);

  doc
    .moveTo(50, 120)
    .lineTo(doc.page.width - 50, 120)
    .stroke();

  doc.y = 140;

  /* =========================
     TITLE
  ========================= */
  doc.fontSize(12).font('Helvetica-Bold').text('GENERAL RECORD OF INTERNS', doc.page.margins.left, doc.y, {
    width: pageWidth,
    align: 'center',
  });

  doc.moveDown(0.5);

  /* =========================
     COMPANY NAME
  ========================= */
  doc
    .fontSize(10)
    .font('Helvetica')
    .text(`Company: ${data.companyName}`, doc.page.margins.left, doc.y, { align: 'center' });

  doc.moveDown(0.3);

  /* =========================
     GENERATED TIMESTAMP
  ========================= */
  const currentDate = new Date().toLocaleString('en-US', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: true,
  });
  doc
    .fontSize(8)
    .font('Helvetica-Oblique')
    .fillColor('#666666')
    .text(`Generated by PUPSINAG (PUP System for Internship Navigation and Guidance) on ${currentDate}`, { align: 'center' });
  doc.fillColor('#000000').font('Helvetica');

  doc.moveDown(0.5);

  /* =========================
     TABLE
  ========================= */
  const tableTop = doc.y;
  const colWidths = {
    studentId: 90,
    fullName: 180,
    email: 180,
    guardian: 130,
    position: 110,
  };

  const rowHeight = 25;
  let currentY = tableTop;

  // Helper function to draw table border
  const drawTableBorder = (x, y, width, height) => {
    doc.rect(x, y, width, height).stroke();
  };

  // Calculate positions
  const startX = 50;
  const studentIdX = startX;
  const fullNameX = studentIdX + colWidths.studentId;
  const emailX = fullNameX + colWidths.fullName;
  const guardianX = emailX + colWidths.email;
  const positionX = guardianX + colWidths.guardian;
  const totalWidth =
    colWidths.studentId + colWidths.fullName + colWidths.email + colWidths.guardian + colWidths.position;

  // TABLE HEADER
  doc.font('Helvetica-Bold').fontSize(9);

  // Draw header background
  doc.fillColor('#8B0000').rect(startX, currentY, totalWidth, rowHeight).fill();

  // Draw header text
  doc.fillColor('#FFFFFF');
  doc.text('STUDENT ID', studentIdX + 5, currentY + 8, { width: colWidths.studentId - 10 });
  doc.text('FULL NAME', fullNameX + 5, currentY + 8, { width: colWidths.fullName - 10 });
  doc.text('EMAIL', emailX + 5, currentY + 8, { width: colWidths.email - 10 });
  doc.text('GUARDIAN', guardianX + 5, currentY + 8, { width: colWidths.guardian - 10 });
  doc.text('POSITION', positionX + 5, currentY + 8, { width: colWidths.position - 10 });

  // Draw header border
  doc.strokeColor('#000000');
  drawTableBorder(startX, currentY, totalWidth, rowHeight);

  currentY += rowHeight;

  // TABLE ROWS
  doc.font('Helvetica').fontSize(8).fillColor('#000000');

  data.students.forEach((student, index) => {
    // Check if we need a new page
    if (currentY + rowHeight > doc.page.height - doc.page.margins.bottom) {
      doc.addPage();
      currentY = doc.page.margins.top;

      // Redraw header on new page
      doc.font('Helvetica-Bold').fontSize(9);
      doc.fillColor('#8B0000').rect(startX, currentY, totalWidth, rowHeight).fill();
      doc.fillColor('#FFFFFF');
      doc.text('STUDENT ID', studentIdX + 5, currentY + 8, { width: colWidths.studentId - 10 });
      doc.text('FULL NAME', fullNameX + 5, currentY + 8, { width: colWidths.fullName - 10 });
      doc.text('EMAIL', emailX + 5, currentY + 8, { width: colWidths.email - 10 });
      doc.text('GUARDIAN', guardianX + 5, currentY + 8, { width: colWidths.guardian - 10 });
      doc.text('POSITION', positionX + 5, currentY + 8, { width: colWidths.position - 10 });
      doc.strokeColor('#000000');
      drawTableBorder(startX, currentY, totalWidth, rowHeight);
      currentY += rowHeight;
      doc.font('Helvetica').fontSize(8).fillColor('#000000');
    }

    // Row background (alternate colors)
    if (index % 2 === 0) {
      doc.fillColor('#F5F5F5').rect(startX, currentY, totalWidth, rowHeight).fill();
      doc.fillColor('#000000');
    }

    // Row data
    doc.text(student.studentId || '-', studentIdX + 5, currentY + 8, { width: colWidths.studentId - 10 });
    doc.text(student.fullName || '-', fullNameX + 5, currentY + 8, { width: colWidths.fullName - 10 });
    doc.text(student.email || '-', emailX + 5, currentY + 8, { width: colWidths.email - 10 });
    doc.text(student.guardian || '-', guardianX + 5, currentY + 8, { width: colWidths.guardian - 10 });
    doc.text(student.position || '-', positionX + 5, currentY + 8, { width: colWidths.position - 10 });

    // Draw row border
    drawTableBorder(startX, currentY, totalWidth, rowHeight);

    currentY += rowHeight;
  });

  doc.end();
};
