/* eslint-env node */
const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

function formatDate(dateString) {
  const date = new Date(dateString);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

module.exports = function generateDailyAttendancePDF(data, res) {
  const doc = new PDFDocument({
    size: 'LETTER',
    margins: { top: 50, bottom: 50, left: 50, right: 50 },
  });

  // Pipe directly to response
  doc.pipe(res);

  const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

  /* =========================
     LOGO
  ========================= */
  const logoPath = path.join(__dirname, '..', 'pup_1904_flat.png');

  if (fs.existsSync(logoPath)) {
    try {
      const imageBuffer = fs.readFileSync(logoPath);
      doc.image(imageBuffer, 50, 50, { width: 55 });
    } catch (err) {
      console.error('❌ Logo error:', err.message);
    }
  }

  /* =========================
     HEADER TEXT
  ========================= */
  doc
    .fontSize(8)
    .text('REPUBLIC OF THE PHILIPPINES', 120, 55)
    .fontSize(10)
    .font('Helvetica-Bold')
    .text('POLYTECHNIC UNIVERSITY OF THE PHILIPPINES', 120, 67)
    .fontSize(8)
    .font('Helvetica')
    .text('OFFICE OF THE VICE PRESIDENT FOR CAMPUSES', 120, 81)
    .fontSize(10)
    .font('Helvetica-Bold')
    .text('MARIVELES, BATAAN CAMPUS', 120, 93);

  doc
    .moveTo(50, 120)
    .lineTo(doc.page.width - 50, 120)
    .stroke();

  doc.y = 140;

  /* =========================
     TITLE
  ========================= */
  doc.fontSize(12).font('Helvetica-Bold').text('DAILY ATTENDANCE', doc.page.margins.left, doc.y, {
    width: pageWidth,
    align: 'center',
  });

  doc.moveDown(0.5);

  /* =========================
     DATE AND COMPANY
  ========================= */
  doc
    .fontSize(10)
    .font('Helvetica')
    .text(`Date: ${formatDate(data.date)}`, doc.page.margins.left, doc.y, { align: 'left' });

  doc.text(`Company: ${data.companyName}`, { align: 'left' });

  doc.moveDown(0.5);

  /* =========================
     GENERATED TIMESTAMP
  ========================= */
  const currentDate = new Date().toLocaleString('en-US', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: true,
  });
  doc
    .fontSize(8)
    .font('Helvetica-Oblique')
    .fillColor('#666666')
    .text(`Generated by PUPSINAG (PUP System for Internship Navigation and Guidance) on ${currentDate}`, { align: 'center' });
  doc.fillColor('#000000').font('Helvetica');

  doc.moveDown(1);

  /* =========================
     TABLE
  ========================= */
  const tableTop = doc.y;
  const colWidths = {
    no: 50,
    name: 250,
    timeIn: 100,
    timeOut: 100,
  };

  const rowHeight = 25;
  let currentY = tableTop;

  // Helper function to draw table border
  const drawTableBorder = (x, y, width, height) => {
    doc.rect(x, y, width, height).stroke();
  };

  // Calculate positions
  const startX = 50;
  const noX = startX;
  const nameX = noX + colWidths.no;
  const timeInX = nameX + colWidths.name;
  const timeOutX = timeInX + colWidths.timeIn;
  const totalWidth = colWidths.no + colWidths.name + colWidths.timeIn + colWidths.timeOut;

  // TABLE HEADER
  doc.font('Helvetica-Bold').fontSize(10);

  // Draw header background
  doc.fillColor('#8B0000').rect(startX, currentY, totalWidth, rowHeight).fill();

  // Draw header text
  doc.fillColor('#FFFFFF');
  doc.text('NO.', noX + 15, currentY + 8, { width: colWidths.no - 10 });
  doc.text('STUDENT NAME', nameX + 10, currentY + 8, { width: colWidths.name - 10 });
  doc.text('TIME IN', timeInX + 10, currentY + 8, { width: colWidths.timeIn - 10 });
  doc.text('TIME OUT', timeOutX + 10, currentY + 8, { width: colWidths.timeOut - 10 });

  // Draw header border
  doc.strokeColor('#000000');
  drawTableBorder(startX, currentY, totalWidth, rowHeight);

  currentY += rowHeight;

  // TABLE ROWS
  doc.font('Times-Roman').fontSize(10).fillColor('#000000');

  data.students.forEach((student, index) => {
    // Check if we need a new page
    if (currentY + rowHeight > doc.page.height - doc.page.margins.bottom) {
      doc.addPage();
      currentY = doc.page.margins.top;

      // Redraw header on new page
      doc.font('Helvetica-Bold').fontSize(10);
      doc.fillColor('#8B0000').rect(startX, currentY, totalWidth, rowHeight).fill();
      doc.fillColor('#FFFFFF');
      doc.text('NO.', noX + 15, currentY + 8, { width: colWidths.no - 10 });
      doc.text('STUDENT NAME', nameX + 10, currentY + 8, { width: colWidths.name - 10 });
      doc.text('TIME IN', timeInX + 10, currentY + 8, { width: colWidths.timeIn - 10 });
      doc.text('TIME OUT', timeOutX + 10, currentY + 8, { width: colWidths.timeOut - 10 });
      doc.strokeColor('#000000');
      drawTableBorder(startX, currentY, totalWidth, rowHeight);
      currentY += rowHeight;
      doc.font('Helvetica').fontSize(10).fillColor('#000000');
    }

    // Row background (alternate colors)
    if (index % 2 === 0) {
      doc.fillColor('#F5F5F5').rect(startX, currentY, totalWidth, rowHeight).fill();
      doc.fillColor('#000000');
    }

    // Row data
    doc.text(`${index + 1}`, noX + 15, currentY + 8, { width: colWidths.no - 10 });
    doc.text(student.name || '', nameX + 10, currentY + 8, { width: colWidths.name - 10 });
    doc.text(student.timeIn || '', timeInX + 10, currentY + 8, { width: colWidths.timeIn - 10 });
    doc.text(student.timeOut || '', timeOutX + 10, currentY + 8, { width: colWidths.timeOut - 10 });

    // Draw row border
    drawTableBorder(startX, currentY, totalWidth, rowHeight);

    currentY += rowHeight;
  });

  doc.end();
};
