const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');

module.exports = async (data) => {
  const fileName = `PUP_NOTARIZED_INTERNSHIP_AGREEMENT_${Date.now()}.pdf`;
  const filePath = path.join(__dirname, '../uploads', fileName);

  // Format dates to "MONTH YEAR" format
  const formatMonthYear = (dateString) => {
    if (!dateString) return '';
    const date = new Date(dateString);
    const monthNames = [
      'JANUARY',
      'FEBRUARY',
      'MARCH',
      'APRIL',
      'MAY',
      'JUNE',
      'JULY',
      'AUGUST',
      'SEPTEMBER',
      'OCTOBER',
      'NOVEMBER',
      'DECEMBER',
    ];
    return `${monthNames[date.getMonth()]} ${date.getFullYear()}`;
  };

  const startDateFormatted = formatMonthYear(data.startDate);
  const endDateFormatted = formatMonthYear(data.endDate);

  const doc = new PDFDocument({
    size: 'Legal',
    margins: { top: 50, left: 50, right: 50, bottom: 50 },
  });

  doc.pipe(fs.createWriteStream(filePath));

  // ========== FOOTER AT TOP ==========
  const currentDate = new Date().toLocaleString('en-US', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: true,
  });
  doc
    .fontSize(8)
    .font('Times-Italic')
    .fillColor('#666666')
    .text(`Generated by PUPSINAG (PUP System for Internship Navigation and Guidance) on ${currentDate}`, { align: 'center' });
  doc.moveDown(1);
  doc.fillColor('#000000').font('Times-Roman');

  /* =====================================================
     PAGE 1 – INTERNSHIP AGREEMENT (MAIN BODY)
  ===================================================== */

  // TITLE
  doc.font('Times-Bold').fontSize(14).text('INTERNSHIP AGREEMENT', { align: 'center' });
  doc.moveDown(2);

  // INTRO PARAGRAPH
  doc
    .font('Times-Roman')
    .fontSize(12)
    .text(
      `I, ${data.studentName}, with the consent of my parent/guardian, ${data.guardian}, ` +
        `a ${data.program} student of the POLYTECHNIC UNIVERSITY OF THE PHILIPPINES, ` +
        `with principal address at Anonas St., Sta. Mesa, Manila, hereinafter referred to as ` +
        `“UNIVERSITY”, as part of the school curriculum or academic requirement voluntarily agrees ` +
        `to undergo On-the-Job Training (OJT)/Internship Program at the ${data.hteName} with office ` +
        `address at ${data.hteAddress}, hereinafter referred to as “HTE”. The On-the-Job Training ` +
        `(OJT)/Internship Program shall start on ${startDateFormatted} and ends on ${endDateFormatted} ` +
        `and is covered by the following terms and conditions:`,
      { align: 'justify', lineGap: 3 },
    );

  doc.moveDown(1.2);

  /* =========================
   1. SCOPE OF AGREEMENT
========================= */
  doc.font('Times-Bold').text('1. Scope of the Agreement. ', { continued: true });
  doc
    .font('Times-Roman')
    .text(
      'This Agreement governs the Internship Program (“Program”) jointly pursued by the Parties ' +
        'in accordance with CHED Memorandum Order No. 104, Series of 2017. Internship refers to the ' +
        'practical application of classroom learning to actual work environment. It is synonymous ' +
        'to Practicum, Field Practice, or On-the-Job Training; it is not synonymous to Apprenticeship ' +
        'and Learnership.',
      { align: 'justify', lineGap: 3 },
    );

  doc.moveDown(0.8);

  /* =========================
   2. DURATION
========================= */
  doc.font('Times-Bold').text('2. Duration of the Internship. ', { continued: true });
  doc
    .font('Times-Roman')
    .text(
      `The duration of the Program shall be a total number of ${data.hours} hours. ` +
        'The internship shall be for a maximum of 8 hours between 8:00 am to 5:00 pm, Mondays to Fridays only. ' +
        'The Student Intern shall not be subjected to mandatory overtime (OT) nor be required to work during holidays.',
      { align: 'justify', lineGap: 3 },
    );

  doc.moveDown(0.8);

  /* =========================
   3. PLACE OF ASSIGNMENT
========================= */
  doc.font('Times-Bold').text('3. Place of Assignment. ', { continued: true });
  doc
    .font('Times-Roman')
    .text(
      'The duties and responsibilities of the Student Intern shall be performed on the premises of the HTE ' +
        'through onsite learning experiences or other modalities subject to the prevailing government issuances ' +
        'and the rules and regulations of the HTE and the University.',
      { align: 'justify', lineGap: 3 },
    );

  doc.moveDown(0.8);

  /* =========================
   4. DUTIES AND RESPONSIBILITIES
========================= */
  doc.font('Times-Bold').text('4. Duties and Responsibilities of the Student Intern. ');
  doc.font('Times-Roman').text('The Student Intern commits to:', { align: 'justify' });

  doc.moveDown(0.5);

  // Lettered items (indented like screenshot)
  const duties = [
    'a. Submit the notarized written consent of the parent/guardian allowing him/her to undergo the Internship Program with the HTE;',
    'b. Undergo the required orientation/training program conducted by the HTE and the University;',
    'c. Complete the agreed duration of his/her internship, and if unable to do so, notify the HTE and the University’s OJT Coordinator in writing of his/her intent and reasons to prematurely end his/her internship at least three (3) days before his/her last day of internship;',
    'd. Submit required practicum/internship documents within the deadline, including a monthly journal of practicum experiences describing his/her training activities, problems encountered, and reflections on the training experience to the OJT Coordinator (if applicable to the course);',
    'e. Perform tasks and activities in accordance with the internship plan;',
    'f. Maintain confidentiality during and after the internship period of all information, data, and business or trade secrets of the HTE where such information is not within the public domain and is indicated or deemed to be confidential and submit a signed Non-Disclosure Agreement prescribed by the HTE as a pre-requisite to participating in the program;',
    'g. Use all information and materials received from the HTE for the sole purpose of performing his/her duties under the internship program;',
    'h. Respect and comply with the relevant rules and regulations of the CHED, the HTE, and the University;',
    'i. Be responsible, together with his/her parents/guardian for any and all loss, damage, injury, expense, proceeding, demand, cost, claim, suit or liability incurred arising from his/her own omission or gross negligence in the performance of his/her duties;',
    'j. Be responsible for any damage caused to the HTE by paying the cost of repair or replacement necessary to restore the property into full operations;',
  ];

  duties.forEach((item) => {
    doc.text(item, {
      align: 'justify',
      indent: 30,
      lineGap: 3,
    });
  });
  doc.moveDown(0.5);

  doc.font('Times-Roman').fontSize(9).text('Page 1 of 3', { align: 'right' });

  doc.addPage();
  /* =====================================================
   PAGE 2 – MISCELLANEOUS & SIGNATURES
===================================================== */

  doc.fontSize(12);

  /* =========================
   k. EXIT ASSESSMENT
========================= */
  doc
    .font('Times-Roman')
    .text(
      'k. Report to the HTE’s focal person and the University’s OJT Coordinator for an exit ' +
        'assessment/interview upon completion of the Program.',
      { align: 'justify', lineGap: 3 },
    );

  doc.moveDown(1);

  /* =========================
   5. MISCELLANEOUS PROVISIONS
========================= */
  doc.font('Times-Bold').text('5. Miscellaneous Provisions');
  doc.moveDown(0.6);

  // a
  doc
    .font('Times-Roman')
    .text(
      'a. Any activity that involves processing of personal data shall comply with the Data Privacy ' +
        'Act of 2012 (Republic Act No. 10173), its Implementing Rules and Regulations, and other ' +
        'applicable laws and administrative issuances. The Parties shall perform any or all actions ' +
        'necessary to facilitate such processing of personal data, including execution of contracts, ' +
        'securing of consent, and other similar or related acts.',
      { align: 'justify', indent: 30, lineGap: 3 },
    );

  doc.moveDown(0.6);

  // b
  doc.text(
    'b. Nothing in this Agreement shall be construed as constituting or evidencing a contract of ' +
      'employment or partnership between the Parties.',
    { align: 'justify', indent: 30, lineGap: 3 },
  );

  doc.moveDown(0.6);

  // c
  doc.text(
    'c. The invalidity or unenforceability of any provision of this Agreement shall not affect or ' +
      'impair the validity, binding effect, or enforceability of the remaining provisions.',
    { align: 'justify', indent: 30, lineGap: 3 },
  );

  doc.moveDown(0.6);

  // d
  doc.text(
    'd. Any dispute arising from this Agreement shall be resolved amicably between the Parties. ' +
      'Only upon failure of amicable settlement may either Party bring the dispute before the ' +
      'appropriate court or tribunal of competent jurisdiction.',
    { align: 'justify', indent: 30, lineGap: 3 },
  );

  doc.moveDown(0.6);

  // e
  doc.text(
    'e. This Agreement shall be governed by and construed in accordance with the laws of the ' +
      'Republic of the Philippines.',
    { align: 'justify', indent: 30, lineGap: 3 },
  );

  doc.moveDown(0.6);

  // f
  doc.text(
    'f. This Agreement may be executed in several counterparts. Each counterpart shall be ' +
      'deemed an original, and all counterparts together shall constitute one and the same ' +
      'Agreement.',
    { align: 'justify', indent: 30, lineGap: 3 },
  );

  doc.moveDown(0.6);

  // g
  doc.text('g. Each Party shall bear the cost of notarization relative to their respective signatories.', {
    align: 'justify',
    indent: 30,
    lineGap: 3,
  });

  doc.moveDown(0.6);

  // h
  doc.text('h. This Agreement shall take effect upon signing by both Parties.', {
    align: 'justify',
    indent: 30,
    lineGap: 3,
  });

  doc.moveDown(2);

  /* =========================
   IN WITNESS WHEREOF
========================= */
  doc.font('Times-Bold').text('IN WITNESS WHEREOF, ', { continued: true });
  doc
    .font('Times-Roman')
    .text(
      'the Parties hereby affix their signatures this _____ day of _____, 20___ at ' +
        '_____________________________, Philippines.',
      { align: 'justify', lineGap: 3 },
    );

  doc.moveDown(3);

  /* =========================
   HTE SIGNATURE
========================= */
  doc.font('Times-Bold').text(data.authorizedRep, { align: 'center' });
  doc.font('Times-Italic').text('(Name of the Authorized Representative of the HTE)', {
    align: 'center',
  });
  doc.font('Times-Roman').text('(Position)', { align: 'center' });
  doc.text(`(${data.hteName})`, { align: 'center' });

  doc.moveDown(4);

  /* =========================
   STUDENT & GUARDIAN SIGNATURES
========================= */
  const pageWidth = doc.page.width;
  const margin = doc.page.margins.left;
  const usableWidth = pageWidth - margin * 2;
  const y = doc.y;

  // LEFT – PARENT / GUARDIAN
  doc.font('Times-Bold').text(data.guardian, margin, y, {
    width: usableWidth / 2 - 20,
  });
  doc.font('Times-Italic').text('(Name of Parent / Guardian)', margin, y + 16, {
    width: usableWidth / 2 - 20,
  });

  // RIGHT – STUDENT INTERN
  doc.font('Times-Bold').text(data.studentName, margin + usableWidth / 2 + 20, y, {
    width: usableWidth / 2 - 20,
    align: 'right',
  });
  doc.font('Times-Italic').text('(Name of Student Intern)', margin + usableWidth / 2 + 20, y + 16, {
    width: usableWidth / 2 - 20,
    align: 'right',
  });

  doc.moveDown(18);
  doc.font('Times-Roman').fontSize(9).text('Page 2 of 3', { align: 'right' });

  doc.addPage();
  /* =====================================================
   PAGE 3 – ACKNOWLEDGMENT
===================================================== */

  /* =========================
   TITLE
========================= */
  doc.font('Times-Bold').fontSize(12).text('ACKNOWLEDGMENT', { align: 'center' });
  doc.moveDown(2);

  /* =========================
   VENUE
========================= */
  doc
    .font('Times-Roman')
    .fontSize(12)
    .text('Republic of the Philippines )\n' + 'City of __________________ ) S.S.\n\n', { align: 'left' });

  /* =========================
   APPEARANCE CLAUSE
========================= */
  doc.font('Times-Bold').text('BEFORE ME, ', { continued: true });
  doc
    .font('Times-Roman')
    .text(
      'a Notary Public, for and in the City of __________________, ' +
        'this _____ day of __________ 20___ personally appeared:',
      { align: 'justify', lineGap: 3 },
    );

  doc.moveDown(1.2);

  /* =========================
   TABLE SETUP
========================= */
  const startX = doc.page.margins.left;
  let startY = doc.y;
  const rowHeight = 34;

  const col1Width = 210; // Names
  const col2Width = 170; // Valid ID
  const col3Width = 110; // Issued at/on
  const tableWidth = col1Width + col2Width + col3Width;

  /* =========================
   TABLE HEADER
========================= */
  doc.rect(startX, startY, tableWidth, rowHeight).stroke();

  doc.font('Times-Bold').fontSize(11);
  doc.text('Name', startX + 6, startY + 10);
  doc.text('Valid Proof of Identity', startX + col1Width + 6, startY + 10);
  doc.text('Issued at/on', startX + col1Width + col2Width + 6, startY + 10);

  /* =========================
   TABLE ROWS
========================= */
  const rows = [
    { name: data.authorizedRep, label: '(Authorized Representative of the HTE)' },
    { name: data.studentName, label: '(Student Intern)' },
    { name: data.guardian, label: '(Parent / Guardian)' },
  ];

  rows.forEach((row, i) => {
    const y = startY + rowHeight * (i + 1);

    doc.rect(startX, y, col1Width, rowHeight).stroke();
    doc.rect(startX + col1Width, y, col2Width, rowHeight).stroke();
    doc.rect(startX + col1Width + col2Width, y, col3Width, rowHeight).stroke();

    doc
      .font('Times-Bold')
      .fontSize(11)
      .text(row.name || '', startX + 6, y + 6);
    doc
      .font('Times-Italic')
      .fontSize(10)
      .text(row.label, startX + 6, y + 20);
  });

  doc.moveDown(6);

  /* =========================
   ACKNOWLEDGMENT TEXT
========================= */
  doc
    .font('Times-Roman')
    .fontSize(12)
    .text(
      'known to me to be the same persons who executed the foregoing instrument and ' +
        'acknowledged the same to me as their free and voluntary act and deed.',
      { align: 'justify', lineGap: 3 },
    );

  doc.moveDown(1);

  doc.text(
    'This instrument consists of three (3) pages, including the page where this ' +
      'Acknowledgment is written, and the parties signed on the left margin of each ' +
      'and every page thereof.',
    { align: 'justify', lineGap: 3 },
  );

  doc.moveDown(1.2);

  /* =========================
   WITNESS CLAUSE
========================= */
  doc.font('Times-Bold').text('WITNESS MY HAND AND SEAL on the place and date first above written.');

  doc.moveDown(2);

  /* =========================
   NOTARY DETAILS
========================= */
  const footerY = doc.y;
  const leftX = startX;
  const rightX = doc.page.width - doc.page.margins.right - 140;

  // LEFT – DOC DETAILS
  doc
    .font('Times-Roman')
    .text('Doc. No. _____;', leftX, footerY)
    .text('Page No. _____;', leftX, footerY + 14)
    .text('Book No. _____;', leftX, footerY + 28)
    .text('Series of _____;', leftX, footerY + 42);

  // RIGHT – NOTARY
  doc.text('Notary Public', rightX, footerY + 42);

  doc.moveDown(28);

  doc.font('Times-Roman').fontSize(9).text('Page 3 of 3', { align: 'right' });

  doc.end();

  return `/uploads/${fileName}`;
};
